version: '3'

services:
### NGINX Server #########################################
    nginx:
      build:
        context: ./nginx
      volumes:
        - ${LARAVEL_PATH}:${LARAVEL_PATH_CONTAINER}
        - ${EXPRESS_PATH}:${EXPRESS_PATH_CONTAINER}
        - ${VUE_PATH}:${VUE_PATH_CONTAINER}
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_SITES_PATH}/${NGINX_SITE_CONFIG_FILE}:/etc/nginx/sites-available/${NGINX_SITE_CONFIG_FILE}
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
      links:
        - php-fpm
    php-fpm:
      build:
        context: ./php-fpm
      volumes:
        - ${LARAVEL_PATH}:${LARAVEL_PATH_CONTAINER}
      links:
        - mysql
        - redis
      environment:
        - "DB_PORT=3306"
        - "DB_HOST=mysql"
        - "REDIS_PORT=6379"
        - "REDIS_HOST=redis"
    mysql:
      image: mysql:5.7
      volumes:
        - ./mysql/storage:/var/lib/mysql
      environment:
        - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
        - "MYSQL_USER=${MYSQL_USER}"
        - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
        - "MYSQL_DATABASE=${MYSQL_DB_NAME}"
      ports:
        - "3306:3306"
    redis:
      image: redis:3.0
      ports:
        - "63791:6379"
    node-frontend:
      build:
        context: ${VUE_PATH}
        dockerfile: docker/Dockerfile
      volumes:
        - ${VUE_PATH}:${VUE_PATH_CONTAINER}
      tty:
        true
    node-backend:
      build:
        context: ${EXPRESS_PATH}
        dockerfile: docker/Dockerfile
      volumes:
        - ${VUE_PATH}:${VUE_PATH_CONTAINER}
        - ${EXPRESS_PATH}:${EXPRESS_PATH_CONTAINER}
      tty:
        true
    workspace:
      build:
        context: ./workspace
      volumes:
        - ${VUE_PATH}:${VUE_PATH_CONTAINER}
        - ${EXPRESS_PATH}:${EXPRESS_PATH_CONTAINER}
        - ${LARAVEL_PATH}:${LARAVEL_PATH_CONTAINER}
      links:
        - node-backend
        - node-frontend
        - php-fpm
        - mysql